-- Schema for the banking component (H2). Applied at startup by DatabaseInitializer.

CREATE TABLE IF NOT EXISTS accounts (
  id            UUID PRIMARY KEY,
  owner_name    VARCHAR(255) NOT NULL,
  currency      CHAR(3)       NOT NULL,
  balance_minor BIGINT        NOT NULL,
  request_key   VARCHAR(128)  UNIQUE,
  CONSTRAINT chk_nonneg CHECK (balance_minor >= 0)
);

CREATE TABLE IF NOT EXISTS transactions (
  id           UUID PRIMARY KEY,
  seq          BIGINT NOT NULL UNIQUE,
  created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
  type         VARCHAR(16) NOT NULL,
  request_key  VARCHAR(128) UNIQUE
);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id UUID   NOT NULL,
  account_id     UUID   NOT NULL,
  currency       CHAR(3) NOT NULL,
  entry_type     VARCHAR(8) NOT NULL,
  signed_amount  BIGINT  NOT NULL,
  ordinal        INT     NOT NULL,
  CONSTRAINT fk_entry_tx FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);

CREATE INDEX IF NOT EXISTS idx_entries_account ON ledger_entries(account_id);
